#!/usr/bin/env bash
# Run ON a DGX box, as that box's user. Produces two things:
#   1. an ENCRYPTED backup of ~/.claude  (stays local — never pushed to the hub)
#   2. a REDACTED inventory -> spark-hub/inventory/<host>_<user>.md  (safe to push)
#
# HARD RULE: this script never prints a secret VALUE. For credentials it emits
# only the key NAME and "<set, len=N>" so existence/shape is proven without leaking.
set -euo pipefail

HUB="$(cd "$(dirname "$0")/.." && pwd)"
HOST="$(hostname -s)"; WHO="$(id -un)"; STAMP="$(date +%Y%m%d_%H%M%S)"
INV="$HUB/inventory/${HOST}_${WHO}.md"
mkdir -p "$HUB/inventory" "$HOME/Claude/Documents"

# ── 1. encrypted backup ─────────────────────────────────────────────────────
DEST="$HOME/Claude/Documents/claude_full_${STAMP}.tar.gz"
tar --warning=no-file-changed -czf "$DEST" -C "$HOME" .claude
SHA="$(sha256sum "$DEST" | awk '{print $1}')"
SESS="$(tar tzf "$DEST" | grep -c '\.jsonl$' || true)"
MEM="$(tar tzf "$DEST"  | grep -c '/memory/.*\.md$' || true)"
SIZE="$(du -h "$DEST" | awk '{print $1}')"
if command -v gpg >/dev/null; then
  gpg -c "$DEST" && shred -u "$DEST" && DEST="${DEST}.gpg"
  echo "[backup] encrypted -> $DEST"
else
  echo "[backup] WARNING: gpg not found — backup left UNENCRYPTED at $DEST" >&2
fi

# ── 2. redacted inventory ───────────────────────────────────────────────────
{
  echo "# Inventory — ${HOST} / ${WHO} — ${STAMP}"
  echo
  echo "_Generated by backup_and_inventory.sh. Secret VALUES are never printed._"
  echo
  echo "## Backup"
  echo "- file: \`$DEST\` (local only, not in hub)"
  echo "- size: $SIZE   sessions: $SESS   memory md: $MEM"
  echo "- sha256: \`$SHA\`"
  echo

  echo "## Services (systemd)"
  echo '```'
  systemctl list-units --type=service --state=running --no-pager --no-legend 2>/dev/null \
    | awk '{print $1, $4}' | head -40 || true
  echo "--- user units ---"
  systemctl --user list-units --type=service --no-pager --no-legend 2>/dev/null \
    | awk '{print $1, $4}' | head -40 || true
  echo '```'
  echo

  echo "## Listening ports"
  echo '```'
  (ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null) | awk 'NR==1 || /LISTEN/' | head -40 || true
  echo '```'
  echo

  echo "## .env files — KEY NAMES ONLY (values redacted)"
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    echo "### \`${f/#$HOME/\~}\`"
    grep -E '^[[:space:]]*(export[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*=' "$f" 2>/dev/null \
      | sed -E 's/^[[:space:]]*(export[[:space:]]+)?//' \
      | while IFS='=' read -r k v; do
          v="${v%\"}"; v="${v#\"}"; len=${#v}
          if [ "$len" -gt 0 ]; then echo "- \`$k\` = <set, len=$len>"; else echo "- \`$k\` = <empty>"; fi
        done
    echo
  done < <(find "$HOME" -maxdepth 5 -type f \( -name '*.env' -o -name '.env' \) \
             ! -path '*/node_modules/*' 2>/dev/null | sort)

  echo "## GAPS — security risks (review + remediate)"
  echo "- [ ] connector tokens visible in \`ps -ef\` (cloudflared etc.) — move to credentials file"
  echo "- [ ] any \`memory/reference_*.md\` holding plaintext secrets (auto-loaded into every session)"
  echo "- [ ] world-readable secret files: $(find "$HOME" -maxdepth 5 -type f \( -name '*.env' -o -name '*credential*' \) -perm -o+r 2>/dev/null | wc -l) found"
  echo
  echo "_End of inventory. Confirm no values leaked before pushing._"
} > "$INV"

echo "[inventory] wrote $INV"
echo "[done] review $INV, then run dgx_push.sh"
